const CAST_ERROR = 400;
const FORBIDDEN_ERROR = 403;
const DOCUMENT_NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  CAST_ERROR,
  DOCUMENT_NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
  DUPLICATE_KEY_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
};
