const CAST_ERROR = 400;
const DOCUMENT_NOT_FOUND_ERROR = 404;
const INTERNAL_SERVER_ERROR = 500;
const DUPLICATE_KEY_ERROR = 11000;

module.exports = { CAST_ERROR, DOCUMENT_NOT_FOUND_ERROR, INTERNAL_SERVER_ERROR, DUPLICATE_KEY_ERROR };